In [1]:
import csv
import os
import pandas as pd

In [12]:
with open('go_aggregated_runs_and_assemblies_full.tsv') as file:
    pd_df = pd.read_csv(file, delimiter='\t')

## Show file

In [13]:
pd_df

,id,study_id,sample_id,biome,exptype,GO:0043130,GO:0055074,GO:0055117,GO:0046933,GO:0006302,...,GO:0019357,GO:0006527,GO:0004114,GO:0046423,GO:0034194,GO:0032183,GO:0007618,GO:0030097,GO:0004520,GO:0033739
0,SRR3650980,MGYS00002076,SRS1493755,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,SRR3650981,MGYS00002076,SRS1493754,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,SRR3650982,MGYS00002076,SRS1493753,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,SRR3650983,MGYS00002076,SRS1493756,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,SRR3650984,MGYS00002076,SRS1493757,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74426,ERZ1694525,MGYS00002035,ERS1030532,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
74427,ERZ1694526,MGYS00002035,ERS1030533,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
74428,ERZ1694527,MGYS00002035,ERS1030534,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
74429,ERZ1694528,MGYS00002035,ERS1030537,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
74430,ERZ1694529,MGYS00002035,ERS1030538,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24

## Start to remove duplicates rows

In [9]:
with open('go_aggregated_runs_and_assemblies_full.tsv', 'r') as in_file:
    with open('go_aggregated_runs_full_removed_duplicates.tsv', 'w') as out_file:
        reader = csv.reader(in_file, delimiter="\t")
        writer = csv.writer(out_file, delimiter="\t")
        header = next(reader)
        writer.writerow(header)
        last_row = next(reader)
        writer.writerow(last_row)
        for row in reader:
            # if current row has same cols as the last row, then remove current row
            if row[1:] == last_row[1:]:
                print("row with run_id({}), sample_id({}) is removed.".format(row[0], row[2]))
            else:
                writer.writerow(row)
                last_row = row
print("file generated!")

row with run_id(ERR1727067), sample_id(ERS1444895) is removed.
row with run_id(ERZ1673966), sample_id(ERS223618) is removed.
row with run_id(ERZ778516), sample_id(SRS2207610) is removed.
row with run_id(ERR2306302), sample_id(ERS2210349) is removed.
row with run_id(SRR1040461), sample_id(SRS509347) is removed.
row with run_id(SRR500498), sample_id(SRS334561) is removed.
row with run_id(SRR500501), sample_id(SRS334563) is removed.
row with run_id(SRR500503), sample_id(SRS334564) is removed.
row with run_id(ERR1366701), sample_id(ERS1122560) is removed.
row with run_id(ERR1366702), sample_id(ERS1122560) is removed.
row with run_id(ERR1366704), sample_id(ERS1122561) is removed.
row with run_id(ERR1366705), sample_id(ERS1122561) is removed.
row with run_id(ERR1366707), sample_id(ERS1122562) is removed.
row with run_id(ERR1366708), sample_id(ERS1122562) is removed.
row with run_id(ERR1366709), sample_id(ERS1122562) is removed.
row with run_id(ERR1366711), sample_id(ERS1122563) is removed.
row with run_id(ERR1366712), sample_id(ERS1122563) is removed.
row with run_id(ERR1366713), sample_id(ERS1122563) is removed.
row with run_id(ERR1366715), sample_id(ERS1122564) is removed.
row with run_id(ERR1366716), sample_id(ERS1122564) is removed.
row with run_id(ERR1366717), sample_id(ERS1122564) is removed.
row with run_id(ERR1366719), sample_id(ERS1122565) is removed.
row with run_id(ERR1366720), sample_id(ERS1122565) is removed.
row with run_id(ERR1366721), sample_id(ERS1122565) is removed.
row with run_id(ERR1366723), sample_id(ERS1122566) is removed.
row with run_id(ERR1366724), sample_id(ERS1122566) is removed.
row with run_id(ERR1366725), sample_id(ERS1122566) is removed.
row with run_id(ERR1366728), sample_id(ERS1122568) is removed.
row with run_id(ERR1366729), sample_id(ERS1122568) is removed.
row with run_id(ERR1366730), sample_id(ERS1122568) is removed.
row with run_id(ERZ529332), sample_id(SRS1648183) is removed.
row with run_id(ERR2738566), sample_id(ERS2652897) is removed.
row with run_id(ERR2738567), sample_id(ERS2652897) is removed.
row with run_id(ERR2738569), sample_id(ERS2652898) is removed.
row with run_id(ERR2738570), sample_id(ERS2652898) is removed.
row with run_id(ERR2738572), sample_id(ERS2652899) is removed.
row with run_id(ERR2738573), sample_id(ERS2652899) is removed.
row with run_id(ERR2738575), sample_id(ERS2652900) is removed.
row with run_id(ERR2738577), sample_id(ERS2652901) is removed.
row with run_id(ERR2738578), sample_id(ERS2652901) is removed.
row with run_id(ERR2738580), sample_id(ERS2652902) is removed.
row with run_id(ERR2738581), sample_id(ERS2652902) is removed.
row with run_id(ERR2738583), sample_id(ERS2652903) is removed.
row with run_id(ERR2738584), sample_id(ERS2652903) is removed.
row with run_id(ERR2738586), sample_id(ERS2652904) is removed.
row with run_id(ERR2738587), sample_id(ERS2652904) is removed.
row with run_id(ERR2738589), sample_id(ERS2652905) is removed.
row with run_id(ERR2738591), sample_id(ERS2652906) is removed.
row with run_id(ERR2738592), sample_id(ERS2652906) is removed.
row with run_id(ERR2738594), sample_id(ERS2652907) is removed.
row with run_id(ERR2738595), sample_id(ERS2652907) is removed.
row with run_id(ERR2738596), sample_id(ERS2652907) is removed.
row with run_id(ERR2738598), sample_id(ERS2652908) is removed.
row with run_id(ERR2738599), sample_id(ERS2652908) is removed.
row with run_id(ERR2738601), sample_id(ERS2652909) is removed.
row with run_id(ERR2738602), sample_id(ERS2652909) is removed.
row with run_id(ERR2738604), sample_id(ERS2652910) is removed.
row with run_id(ERR2738605), sample_id(ERS2652910) is removed.
row with run_id(ERR2738607), sample_id(ERS2652911) is removed.
row with run_id(ERR2738608), sample_id(ERS2652911) is removed.
row with run_id(ERR2738610), sample_id(ERS2652912) is removed.
row with run_id(ERR2738611), sample_id(ERS2652912) is removed.
row with run_id(ERR2738613), sample_id(ERS2652913) is removed.
row with run_id(ERR2738614), sample_id(ERS2652913) is removed.
row with run_id(ERR2738616), sample_id(ERS2652914) is removed.
row with run_id(ERR2738617), sample_id(ERS2652914) is removed.
row with run_id(ERR2738619), sample_id(ERS2652915) is removed.
row with run_id(ERR2738620), sample_id(ERS2652915) is removed.
row with run_id(ERR2738621), sample_id(ERS2652915) is removed.
row with run_id(ERR2738623), sample_id(ERS2652916) is removed.
row with run_id(ERR2738624), sample_id(ERS2652916) is removed.
row with run_id(ERR2738626), sample_id(ERS2652917) is removed.
row with run_id(ERR2738627), sample_id(ERS2652917) is removed.
row with run_id(ERR2738629), sample_id(ERS2652918) is removed.
row with run_id(ERR2738630), sample_id(ERS2652918) is removed.
row with run_id(ERR2738632), sample_id(ERS2652919) is removed.
row with run_id(ERR2738633), sample_id(ERS2652919) is removed.
row with run_id(ERR2738635), sample_id(ERS2652920) is removed.
row with run_id(ERR2738636), sample_id(ERS2652920) is removed.
row with run_id(ERR2738638), sample_id(ERS2652921) is removed.
row with run_id(ERR2738639), sample_id(ERS2652921) is removed.
row with run_id(ERR2738640), sample_id(ERS2652921) is removed.
row with run_id(ERR2738641), sample_id(ERS2652921) is removed.
row with run_id(ERR2738643), sample_id(ERS2652922) is removed.
row with run_id(ERR2738644), sample_id(ERS2652922) is removed.
row with run_id(ERR2738645), sample_id(ERS2652922) is removed.
row with run_id(ERR2738647), sample_id(ERS2652923) is removed.
row with run_id(ERR2738648), sample_id(ERS2652923) is removed.
row with run_id(ERR2738649), sample_id(ERS2652923) is removed.
row with run_id(ERR2738650), sample_id(ERS2652923) is removed.
row with run_id(ERR2738652), sample_id(ERS2652924) is removed.
row with run_id(ERR2738653), sample_id(ERS2652924) is removed.
row with run_id(ERR2738654), sample_id(ERS2652924) is removed.
row with run_id(ERR2738656), sample_id(ERS2652925) is removed.
row with run_id(ERR2738657), sample_id(ERS2652925) is removed.
row with run_id(ERR2738658), sample_id(ERS2652925) is removed.
row with run_id(ERR2738659), sample_id(ERS2652925) is removed.
row with run_id(ERR2738661), sample_id(ERS2652926) is removed.
row with run_id(ERR2738662), sample_id(ERS2652926) is removed.
row with run_id(ERR2738663), sample_id(ERS2652926) is removed.
row with run_id(ERR2738665), sample_id(ERS2652927) is removed.
row with run_id(ERR2738666), sample_id(ERS2652927) is removed.
row with run_id(ERR2738668), sample_id(ERS2652928) is removed.
row with run_id(ERR2738669), sample_id(ERS2652928) is removed.
row with run_id(ERR2738670), sample_id(ERS2652928) is removed.
row with run_id(ERR2738672), sample_id(ERS2652929) is removed.
row with run_id(ERR2738673), sample_id(ERS2652929) is removed.
row with run_id(ERR2738674), sample_id(ERS2652929) is removed.
row with run_id(ERR2738675), sample_id(ERS2652929) is removed.
row with run_id(ERR2738676), sample_id(ERS2652929) is removed.
row with run_id(ERR2738678), sample_id(ERS2652930) is removed.
row with run_id(ERR2738679), sample_id(ERS2652930) is removed.
row with run_id(ERR2738680), sample_id(ERS2652930) is removed.
row with run_id(ERR2738681), sample_id(ERS2652930) is removed.
row with run_id(ERR2738682), sample_id(ERS2652930) is removed.
row with run_id(ERR2738684), sample_id(ERS2652931) is removed.
row with run_id(ERR2738685), sample_id(ERS2652931) is removed.
row with run_id(ERR2738686), sample_id(ERS2652931) is removed.
row with run_id(ERR2738687), sample_id(ERS2652931) is removed.
row with run_id(ERR2738689), sample_id(ERS2652932) is removed.
row with run_id(ERR2738690), sample_id(ERS2652932) is removed.
row with run_id(ERR2738691), sample_id(ERS2652932) is removed.
row with run_id(ERR2738692), sample_id(ERS2652932) is removed.
row with run_id(ERR2738694), sample_id(ERS2652933) is removed.
row with run_id(ERR2738695), sample_id(ERS2652933) is removed.
row with run_id(ERR2738696), sample_id(ERS2652933) is removed.
row with run_id(ERR2738698), sample_id(ERS2652934) is removed.
row with run_id(ERR2738699), sample_id(ERS2652934) is removed.
row with run_id(ERR2738700), sample_id(ERS2652934) is removed.
row with run_id(ERR2738701), sample_id(ERS2652934) is removed.
row with run_id(ERR2738702), sample_id(ERS2652934) is removed.
row with run_id(ERR2738703), sample_id(ERS2652934) is removed.
row with run_id(ERR2738705), sample_id(ERS2652935) is removed.
row with run_id(ERR2738706), sample_id(ERS2652935) is removed.
row with run_id(ERR2738707), sample_id(ERS2652935) is removed.
row with run_id(ERR2738709), sample_id(ERS2652936) is removed.
row with run_id(ERR2738710), sample_id(ERS2652936) is removed.
row with run_id(ERR2738711), sample_id(ERS2652936) is removed.
row with run_id(ERR2738712), sample_id(ERS2652936) is removed.
row with run_id(ERR2738713), sample_id(ERS2652936) is removed.
row with run_id(ERR2738715), sample_id(ERS2652937) is removed.
row with run_id(ERR2738716), sample_id(ERS2652937) is removed.
row with run_id(ERR2738717), sample_id(ERS2652937) is removed.
row with run_id(ERR2738718), sample_id(ERS2652937) is removed.
row with run_id(ERR2738719), sample_id(ERS2652937) is removed.
row with run_id(ERR2738721), sample_id(ERS2652938) is removed.
row with run_id(ERR2738722), sample_id(ERS2652938) is removed.
row with run_id(ERR2738723), sample_id(ERS2652938) is removed.
row with run_id(ERR2738724), sample_id(ERS2652938) is removed.
row with run_id(ERR2738725), sample_id(ERS2652938) is removed.
row with run_id(ERR2738726), sample_id(ERS2652938) is removed.
row with run_id(ERR2738728), sample_id(ERS2652939) is removed.
row with run_id(ERR2738729), sample_id(ERS2652939) is removed.
row with run_id(ERR2738730), sample_id(ERS2652939) is removed.
row with run_id(ERR2738731), sample_id(ERS2652939) is removed.
row with run_id(ERR2738733), sample_id(ERS2652940) is removed.
row with run_id(ERR2738734), sample_id(ERS2652940) is removed.
row with run_id(ERR2738735), sample_id(ERS2652940) is removed.
row with run_id(ERR2738736), sample_id(ERS2652940) is removed.
row with run_id(ERR2738737), sample_id(ERS2652940) is removed.
row with run_id(ERR2738739), sample_id(ERS2652941) is removed.
row with run_id(ERR2738740), sample_id(ERS2652941) is removed.
row with run_id(ERR2738741), sample_id(ERS2652941) is removed.
row with run_id(ERR2738742), sample_id(ERS2652941) is removed.
row with run_id(ERR2738744), sample_id(ERS2652942) is removed.
row with run_id(ERR2738745), sample_id(ERS2652942) is removed.
row with run_id(ERR2738746), sample_id(ERS2652942) is removed.
row with run_id(ERR2738747), sample_id(ERS2652942) is removed.
row with run_id(ERR2738749), sample_id(ERS2652943) is removed.
row with run_id(ERR2738750), sample_id(ERS2652943) is removed.
row with run_id(ERR2738751), sample_id(ERS2652943) is removed.
row with run_id(ERR2738753), sample_id(ERS2652944) is removed.
row with run_id(ERR2738754), sample_id(ERS2652944) is removed.
row with run_id(ERR2738755), sample_id(ERS2652944) is removed.
row with run_id(ERR2738757), sample_id(ERS2652945) is removed.
row with run_id(ERR2738758), sample_id(ERS2652945) is removed.
row with run_id(ERR2738759), sample_id(ERS2652945) is removed.
row with run_id(ERR2738760), sample_id(ERS2652945) is removed.
row with run_id(ERR2738761), sample_id(ERS2652945) is removed.
row with run_id(ERR2738763), sample_id(ERS2652946) is removed.
row with run_id(ERR2738764), sample_id(ERS2652946) is removed.
row with run_id(ERR2738765), sample_id(ERS2652946) is removed.
row with run_id(ERR2738767), sample_id(ERS2652947) is removed.
row with run_id(ERR2738768), sample_id(ERS2652947) is removed.
row with run_id(ERR2738769), sample_id(ERS2652947) is removed.
row with run_id(ERR2738770), sample_id(ERS2652947) is removed.
row with run_id(ERR2738772), sample_id(ERS2652948) is removed.
row with run_id(ERR2738773), sample_id(ERS2652948) is removed.
row with run_id(ERR2738774), sample_id(ERS2652948) is removed.
row with run_id(ERR2738775), sample_id(ERS2652948) is removed.
row with run_id(ERR2738776), sample_id(ERS2652948) is removed.
row with run_id(ERR2738777), sample_id(ERS2652948) is removed.
row with run_id(ERR2738779), sample_id(ERS2652949) is removed.
row with run_id(ERR2738780), sample_id(ERS2652949) is removed.
row with run_id(ERR2738781), sample_id(ERS2652949) is removed.
row with run_id(ERR2738782), sample_id(ERS2652949) is removed.
row with run_id(ERR2738783), sample_id(ERS2652949) is removed.
row with run_id(ERR2738785), sample_id(ERS2652950) is removed.
row with run_id(ERR2738786), sample_id(ERS2652950) is removed.
row with run_id(ERR2738787), sample_id(ERS2652950) is removed.
row with run_id(ERR2738788), sample_id(ERS2652950) is removed.
row with run_id(ERR2738789), sample_id(ERS2652950) is removed.
row with run_id(ERR2738791), sample_id(ERS2652951) is removed.
row with run_id(ERR2738792), sample_id(ERS2652951) is removed.
row with run_id(ERR2738793), sample_id(ERS2652951) is removed.
row with run_id(ERR2738794), sample_id(ERS2652951) is removed.
row with run_id(ERR2738796), sample_id(ERS2652952) is removed.
row with run_id(ERR2738797), sample_id(ERS2652952) is removed.
row with run_id(ERR2738798), sample_id(ERS2652952) is removed.
row with run_id(ERR2738799), sample_id(ERS2652952) is removed.
row with run_id(ERR2738800), sample_id(ERS2652952) is removed.
row with run_id(ERR2738802), sample_id(ERS2652953) is removed.
row with run_id(ERR2738803), sample_id(ERS2652953) is removed.
row with run_id(ERR2738804), sample_id(ERS2652953) is removed.
row with run_id(ERR2738805), sample_id(ERS2652953) is removed.
row with run_id(ERR2738806), sample_id(ERS2652953) is removed.
row with run_id(ERR2738807), sample_id(ERS2652953) is removed.
row with run_id(ERR2738809), sample_id(ERS2652954) is removed.
row with run_id(ERR2738810), sample_id(ERS2652954) is removed.
row with run_id(ERR2738811), sample_id(ERS2652954) is removed.
row with run_id(ERR2738812), sample_id(ERS2652954) is removed.
row with run_id(ERR2738814), sample_id(ERS2652955) is removed.
row with run_id(ERR2738815), sample_id(ERS2652955) is removed.
row with run_id(ERR2738816), sample_id(ERS2652955) is removed.
row with run_id(ERR2738817), sample_id(ERS2652955) is removed.
row with run_id(ERR2738819), sample_id(ERS2652956) is removed.
row with run_id(ERR2738820), sample_id(ERS2652956) is removed.
row with run_id(ERR2738821), sample_id(ERS2652956) is removed.
row with run_id(ERR2738822), sample_id(ERS2652956) is removed.
row with run_id(ERR2738824), sample_id(ERS2652957) is removed.
row with run_id(ERR2738825), sample_id(ERS2652957) is removed.
row with run_id(ERR2738826), sample_id(ERS2652957) is removed.
row with run_id(ERR2738827), sample_id(ERS2652957) is removed.
row with run_id(ERR2738828), sample_id(ERS2652957) is removed.
row with run_id(ERR2738829), sample_id(ERS2652957) is removed.
row with run_id(ERR2738831), sample_id(ERS2652958) is removed.
row with run_id(ERR2738832), sample_id(ERS2652958) is removed.
row with run_id(ERR2738833), sample_id(ERS2652958) is removed.
row with run_id(ERR2738834), sample_id(ERS2652958) is removed.
row with run_id(ERR2738835), sample_id(ERS2652958) is removed.
row with run_id(ERR2738836), sample_id(ERS2652958) is removed.
row with run_id(ERR2738838), sample_id(ERS2652959) is removed.
row with run_id(ERR2738839), sample_id(ERS2652959) is removed.
row with run_id(ERR2738840), sample_id(ERS2652959) is removed.
row with run_id(ERR2738841), sample_id(ERS2652959) is removed.
row with run_id(ERR2738842), sample_id(ERS2652959) is removed.
row with run_id(ERR2738844), sample_id(ERS2652960) is removed.
row with run_id(ERR2738845), sample_id(ERS2652960) is removed.
row with run_id(ERR2738846), sample_id(ERS2652960) is removed.
row with run_id(ERR2738847), sample_id(ERS2652960) is removed.
row with run_id(ERR2738849), sample_id(ERS2652961) is removed.
row with run_id(ERR2738850), sample_id(ERS2652961) is removed.
row with run_id(ERR2738851), sample_id(ERS2652961) is removed.
row with run_id(ERR2738852), sample_id(ERS2652961) is removed.
row with run_id(ERR2738853), sample_id(ERS2652961) is removed.
row with run_id(ERR2738855), sample_id(ERS2652962) is removed.
row with run_id(ERR2738856), sample_id(ERS2652962) is removed.
row with run_id(ERR2738857), sample_id(ERS2652962) is removed.
row with run_id(ERR2738858), sample_id(ERS2652962) is removed.
row with run_id(ERR2738859), sample_id(ERS2652962) is removed.
row with run_id(ERR2738860), sample_id(ERS2652962) is removed.
row with run_id(ERR2738862), sample_id(ERS2652963) is removed.
row with run_id(ERR2738863), sample_id(ERS2652963) is removed.
row with run_id(ERR2738864), sample_id(ERS2652963) is removed.
row with run_id(ERR2738865), sample_id(ERS2652963) is removed.
row with run_id(ERR2738866), sample_id(ERS2652963) is removed.
row with run_id(ERR2738868), sample_id(ERS2652964) is removed.
row with run_id(ERR2738869), sample_id(ERS2652964) is removed.
row with run_id(ERR2738870), sample_id(ERS2652964) is removed.
row with run_id(ERR2738871), sample_id(ERS2652964) is removed.
row with run_id(ERR2738872), sample_id(ERS2652964) is removed.
row with run_id(ERR2738874), sample_id(ERS2652965) is removed.
row with run_id(ERR2738875), sample_id(ERS2652965) is removed.
row with run_id(ERR2738876), sample_id(ERS2652965) is removed.
row with run_id(ERR2738877), sample_id(ERS2652965) is removed.
row with run_id(ERR2738878), sample_id(ERS2652965) is removed.
row with run_id(ERR2738879), sample_id(ERS2652965) is removed.
row with run_id(ERR2738881), sample_id(ERS2652966) is removed.
row with run_id(ERR2738882), sample_id(ERS2652966) is removed.
row with run_id(ERR2738883), sample_id(ERS2652966) is removed.
row with run_id(ERR2738885), sample_id(ERS2652967) is removed.
row with run_id(ERR2738886), sample_id(ERS2652967) is removed.
row with run_id(ERR2738887), sample_id(ERS2652967) is removed.
row with run_id(ERR2738888), sample_id(ERS2652967) is removed.
row with run_id(ERR2738889), sample_id(ERS2652967) is removed.
row with run_id(ERR2738890), sample_id(ERS2652967) is removed.
row with run_id(ERR2738892), sample_id(ERS2652968) is removed.
row with run_id(ERR2738893), sample_id(ERS2652968) is removed.
row with run_id(ERR2738894), sample_id(ERS2652968) is removed.
row with run_id(ERR2738895), sample_id(ERS2652968) is removed.
row with run_id(ERR2738897), sample_id(ERS2652977) is removed.
row with run_id(ERR2738898), sample_id(ERS2652977) is removed.
row with run_id(ERR2738899), sample_id(ERS2652977) is removed.
row with run_id(ERR2738900), sample_id(ERS2652977) is removed.
row with run_id(ERR2738901), sample_id(ERS2652977) is removed.
row with run_id(ERR2738903), sample_id(ERS2652978) is removed.
row with run_id(ERR2738904), sample_id(ERS2652978) is removed.
row with run_id(ERR2738905), sample_id(ERS2652978) is removed.
row with run_id(ERR2738906), sample_id(ERS2652978) is removed.
row with run_id(ERR2738907), sample_id(ERS2652978) is removed.
row with run_id(ERR2738909), sample_id(ERS2652979) is removed.
row with run_id(ERR2738910), sample_id(ERS2652979) is removed.
row with run_id(ERR2738911), sample_id(ERS2652979) is removed.
row with run_id(ERR2738912), sample_id(ERS2652979) is removed.
row with run_id(ERR2738914), sample_id(ERS2652980) is removed.
row with run_id(ERR2738915), sample_id(ERS2652980) is removed.
row with run_id(ERR2738916), sample_id(ERS2652980) is removed.
row with run_id(ERR2738917), sample_id(ERS2652980) is removed.
row with run_id(ERR2738918), sample_id(ERS2652980) is removed.
row with run_id(ERR2738919), sample_id(ERS2652980) is removed.
row with run_id(ERR2738921), sample_id(ERS2652981) is removed.
row with run_id(ERR2738922), sample_id(ERS2652981) is removed.
row with run_id(ERR2738923), sample_id(ERS2652981) is removed.
row with run_id(ERR2738924), sample_id(ERS2652981) is removed.
row with run_id(ERR2738925), sample_id(ERS2652981) is removed.
row with run_id(ERR2738926), sample_id(ERS2652981) is removed.
row with run_id(ERR2738927), sample_id(ERS2652981) is removed.

## Show new generated file

In [10]:
with open('go_aggregated_runs_full_removed_duplicates.tsv', 'r') as f:
    pd_df = pd.read_csv(f, delimiter='\t')
    pd_df

In [11]:
pd_df

,id,study_id,sample_id,biome,exptype,GO:0043130,GO:0055074,GO:0055117,GO:0046933,GO:0006302,...,GO:0019357,GO:0006527,GO:0004114,GO:0046423,GO:0034194,GO:0032183,GO:0007618,GO:0030097,GO:0004520,GO:0033739
0,SRR3650980,MGYS00002076,SRS1493755,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,SRR3650981,MGYS00002076,SRS1493754,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,SRR3650982,MGYS00002076,SRS1493753,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,SRR3650983,MGYS00002076,SRS1493756,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,SRR3650984,MGYS00002076,SRS1493757,root:Host-associated:Mammals:Respiratory syste...,unknown,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64598,ERZ1694525,MGYS00002035,ERS1030532,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
64599,ERZ1694526,MGYS00002035,ERS1030533,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
64600,ERZ1694527,MGYS00002035,ERS1030534,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
64601,ERZ1694528,MGYS00002035,ERS1030537,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24
64602,ERZ1694529,MGYS00002035,ERS1030538,root:Environmental:Aquatic:Freshwater:Ice:Glacier,assembly,1,0,0,149,6,...,0,45,0,0,10,0,0,0,45,24